/* 第二關後續程序：同一套實體文件元件與獨立場景。 */
let g2={stage:null,selected:null,agenda:[],branch:{},sign:18,pieces:[],order:[],folder:[]};
const gc=s=>document.querySelector(s),G2B=id=>LEVEL2_CONTENT.bills[id];
function g2Token(id){let b=G2B(id),o=GATE2_BILL_OBJECTS[id],marks=o.marks.map(x=>`<i>${x}</i>`).join('');return`<button class="flow-bill ${id}" data-doc="${id}" onclick="g2Pick('${id}')"><small>${b.tag}</small><b>${b.name}</b><em>${marks}</em></button>`}
function g2Pick(x){g2.selected=x;document.querySelectorAll('[data-doc]').forEach(e=>e.classList.toggle('picked',e.dataset.doc===x))}
function g2Drop(zone){if(!g2.selected)return;let x=g2.selected;g2.selected=null;g2Act(x,zone)}
function g2Stamp(id,text){let o=GATE2_BILL_OBJECTS[id];if(!o.marks.includes(text))o.marks.push(text)}function g2Folder(name){if(!g2.folder.includes(name))g2.folder.push(name)}
openGate2Folder=function(){modal(`<button class="close" onclick="document.querySelector('#modal')?.remove()">×</button><div class="gate2-folder-panel"><h2>文件夾</h2>${g2.folder.length?g2.folder.map(x=>`<p class="folder-row">▰ ${x}</p>`).join(''):'<p>目前沒有收入程序文件。</p>'}</div>`)};
function g2Hud(){return`<header class="gate2-hud"><div class="mission"><b>貳｜尚未完成的法案</b><br><span>立法程序紀錄</span></div><button class="folder-hud" onclick="openGate2Folder()" aria-label="開啟文件夾">▰<small>文件夾</small></button></header>`}
function g2Scene(kind,body){app.innerHTML=`<section class="flow-scene ${kind}">${g2Hud()}<main class="flow-table"><div class="flow-title">${kind==='committee'?'委員會會議室':kind==='negotiation'?'黨團協商':'立法院議場'}</div>${body}</main><div class="flow-message" id="flow-message"></div></section>`;bindFlowDrag()}function g2Msg(t){let e=gc('#flow-message');if(e)e.textContent=t}function g2Next(stage,msg){g2.stage=stage;g2Msg(msg||'');setTimeout(g2Render,msg?850:0)}function g2Render(){({agenda,first,branch,committee,committeeexit,direct,directexit,negotiation,second,third,promulgation,effective,complete}[g2.stage]||agenda)()}
function agenda(){g2Scene('chamber',`<article class="agenda-paper" data-zone="agenda" onclick="g2Drop('agenda')"><h2>議事日程</h2><p>程序委員會紀錄</p><p>待排入院會議程的法律案</p><div class="agenda-slots">${g2.agenda.map(x=>`<span>${G2B(x).tag}　✓</span>`).join('')||'<span>文件盤（空）</span>'}</div></article><div class="flow-bills">${g2Token('blue')}${g2Token('orange')}</div><span class="task-hint flow-hint visible"><i></i>查看議事日程</span>`)}
function first(){g2Scene('chamber',`<article class="reading-record"><h2>第一讀會</h2><p>主席台前的程序紀錄</p></article><div class="paper-slips">${['朗讀議案標題','逐條討論','全案表決'].map(x=>`<button onclick="g2First('${x}')">${x}</button>`).join('')}</div>`)}function g2First(x){if(x!=='朗讀議案標題')return g2Msg('程序還沒有走到這裡。');g2Stamp('blue','一讀完成');g2Stamp('orange','一讀完成');g2Next('branch','第一讀會完成。')}
function branch(){g2Scene('chamber',`<div class="branch-record"><p>行政院案：交付委員會審查</p><p>委員案：有人提議逕付二讀</p></div><div class="flow-bills">${g2Token('blue')}${g2Token('orange')}</div><div class="drop-pair"><button data-zone="committee" onclick="g2Drop('committee')">交付委員會審查</button><button data-zone="direct" onclick="g2Drop('direct')">逕付二讀程序</button></div>`)}
function committee(){g2Scene('committee',`<p class="scene-caption">整理委員會審查文件</p><div class="review-folder" data-zone="review" onclick="g2Drop('review')">委員會審查資料夾<br><small>${g2.review||0} / 3</small></div><div class="paper-slips"><button data-doc="review:修正意見" onclick="g2Pick('review:修正意見')">修正意見</button><button data-doc="review:保留意見" onclick="g2Pick('review:保留意見')">保留意見</button><button data-doc="review:審查資料" onclick="g2Pick('review:審查資料')">審查資料</button></div>`)}
function committeeexit(){g2Scene('committee',`<article class="review-report"><h2>委員會審查報告</h2><p>本案部分條文仍有爭議，決議交付黨團協商。</p></article>${g2Token('blue')}<div class="drop-pair"><button data-zone="second" onclick="g2Drop('second')">第二讀會</button><button data-zone="negotiation" onclick="g2Drop('negotiation')">黨團協商</button></div>`)}
function direct(){g2Scene('chamber',`<article class="signature-book"><h2>逕付二讀程序紀錄</h2><p>有人提議 ✓</p><p>連署／附議：<b>${g2.sign} / 20</b></p></article><div class="name-strips">${['林委員','許委員','周委員','方委員','吳委員'].map((x,i)=>`<button data-doc="sign${i}" onclick="g2Pick('sign${i}')">${x}</button>`).join('')}</div><button class="signature-tray" data-zone="sign" onclick="g2Drop('sign')">連署名冊</button><button class="vote-device" ${g2.sign>=20?'':'disabled'} onclick="g2Vote()">院會表決</button>`)}function g2Vote(){g2Stamp('orange','逕付二讀');g2Next('directexit','院會表決：通過。')}
function directexit(){g2Scene('chamber',`${g2Token('orange')}<article class="direct-note">逕付二讀之議案，應交付黨團協商。</article><div class="drop-pair"><button data-zone="second" onclick="g2Drop('second')">第二讀會</button><button data-zone="negotiation" onclick="g2Drop('negotiation')">黨團協商</button></div>`)}
function negotiation(){g2Scene('negotiation',`<p class="scene-caption">修復被拆開的黨團協商結論。</p><div class="paper-slips">${['文件抬頭','協商內容','簽署／結論'].map((x,i)=>`<button data-doc="piece${i}" onclick="g2Pick('piece${i}')">${x}</button>`).join('')}</div><button class="conclusion-sheet" data-zone="piece" onclick="g2Drop('piece')">${g2.pieces.join('　')||'黨團協商結論'}</button>`)}
function second(){g2Scene('chamber',`<p class="scene-caption">第二讀會：依序排回程序紙條。</p><div class="paper-slips">${['廣泛討論','逐條討論','條文議決'].map(x=>`<button data-doc="order:${x}" onclick="g2Pick('order:${x}')">${x}</button>`).join('')}</div><button class="conclusion-sheet" data-zone="order" onclick="g2Drop('order')">${g2.order.map((x,i)=>`${i+1}. ${x}`).join('<br>')||'1.　<br>2.　<br>3.　'}</button>`)}
function third(){g2Scene('chamber dark',`<article class="third-paper"><h2>第三讀會</h2><p>原文：「違反者處新臺幣一萬元罰鍰。」</p><p>修正：「違反者處新臺幣十萬元罰鍰。」</p><button onclick="g2Third('reject')">退回</button><button onclick="g2Third('accept-big')">接受修正</button></article>${g2.third===1?'<article class="third-paper"><p>「應予以通知」 → 「應通知」</p><button onclick="g2Third(\'accept-small\')">接受文字修正</button><button onclick="g2Third(\'reject-small\')">退回</button></article>':''}${g2.third===2?'<button class="vote-device" onclick="g2ThirdVote()">全案表決</button>':''}`)}function g2Third(x){if(x==='accept-big')return g2Msg('這不只是文字修正。');if(x==='reject'){g2.third=1;return g2Render()}if(x==='accept-small'){g2.third=2;return g2Render()}g2Msg('這是文字修正，可接受。')}function g2ThirdVote(){g2Stamp('blue','三讀通過');g2Stamp('orange','三讀通過');g2Next('promulgation','三讀通過。')}
function promulgation(){g2Scene('chamber',`<article class="formal-envelope"><h2>三讀通過</h2><p>三讀通過 ✓<br>公布 □<br>生效 □</p><button onclick="g2Msg('三讀通過，還不是法律生效。')">完成</button><p>立法院咨請總統公布</p><button class="btn light" onclick="g2Next('effective','確認公布紀錄：10月12日。')">確認公布紀錄</button></article>`)}
function effective(){g2Scene('chamber',`<p class="scene-caption">把「生效」印章蓋在正確日期。</p><button class="ink" data-doc="effective" onclick="g2Pick('effective')">生效</button><div class="calendar">${['10/12|公布｜第一日','10/13|第二日','10/14|第三日','10/15|'].map((x,i)=>{let a=x.split('|');return`<button data-zone="date${i}" onclick="g2Drop('date${i}')"><b>${a[0]}</b><small>${a[1]}</small></button>`}).join('')}</div>`)}
function complete(){g2Scene('chamber',`<article class="completion-paper"><div class="stampbig">程序完成</div><h2>提案 → 程序委員會 → 一讀 → 分流</h2><p>行政院案：委員會審查 → 本案交付協商<br>委員案：逕付二讀 → 黨團協商【必經】<br>→ 二讀 → 三讀 → 總統公布 → 生效</p><button class="btn light" onclick="notebook02()">公民筆記02｜立法程序</button><button class="btn" onclick="gate2TestEntry()">重新測試第二關</button></article>`)}
function g2Act(x,z){if(g2.stage==='agenda'&&z==='agenda'&&(x==='blue'||x==='orange')){if(!g2.agenda.includes(x))g2.agenda.push(x);if(g2.agenda.length===2){g2Stamp('blue','議事日程審定');g2Stamp('orange','議事日程審定');return g2Next('first','兩案已排入院會議程。')}return g2Render()}if(g2.stage==='branch'){let ok=(x==='blue'&&z==='committee')||(x==='orange'&&z==='direct');if(!ok)return g2Msg('這份議案的程序紀錄不是這樣。');g2.branch[x]=z;if(g2.branch.blue&&g2.branch.orange){g2.stage='committee';return g2Render()}return g2Render()}if(g2.stage==='committee'&&x.startsWith('review:')&&z==='review'){g2.review=(g2.review||0)+1;if(g2.review===3){g2Folder('委員會審查報告');g2Stamp('blue','審查完竣');return g2Next('committeeexit','取得：委員會審查報告')}return g2Render()}if(g2.stage==='committeeexit'){if(z!=='negotiation')return g2Msg('看看這份審查紀錄。');return g2Next('direct','行政院案已交付黨團協商。')}if(g2.stage==='direct'&&x.startsWith('sign')&&z==='sign'){g2.sign=Math.min(20,g2.sign+1);return g2Render()}if(g2.stage==='directexit'){if(z!=='negotiation')return g2Msg('程序還少了一步。');return g2Next('negotiation','兩案在黨團協商會合。')}if(g2.stage==='negotiation'&&x.startsWith('piece')&&z==='piece'){let p=['文件抬頭','協商內容','簽署／結論'][+x.slice(5)];if(!g2.pieces.includes(p))g2.pieces.push(p);if(g2.pieces.length===3){g2Folder('黨團協商結論');return g2Next('second','黨團協商完成。')}return g2Render()}if(g2.stage==='second'&&x.startsWith('order:')&&z==='order'){let p=x.slice(6);if(!g2.order.includes(p))g2.order.push(p);if(g2.order.length===3){if(g2.order.join('|')!=='廣泛討論|逐條討論|條文議決'){g2.order=[];g2Msg('程序順序似乎不對。');return setTimeout(g2Render,600)}g2Stamp('blue','二讀完成');g2Stamp('orange','二讀完成');return g2Next('third','第二讀會完成。')}return g2Render()}if(g2.stage==='effective'&&x==='effective'){if(z!=='date2')return g2Msg('再看一次公布日的起算方式。');g2Folder('公布紀錄');return g2Next('complete','法律生效 ✓　10/12第一日、10/13第二日、10/14第三日。')}}
function bindFlowDrag(){document.querySelectorAll('[data-doc]').forEach(e=>e.addEventListener('pointerdown',v=>{g2Pick(e.dataset.doc);e.setPointerCapture?.(v.pointerId);v.preventDefault()}));document.querySelectorAll('[data-zone]').forEach(e=>e.addEventListener('pointerup',v=>{g2Drop(e.dataset.zone);v.preventDefault()}))}
const oldReturn=returnProposal;returnProposal=function(id){oldReturn(id);if(GATE2_BILL_OBJECTS.blue.viewed&&GATE2_BILL_OBJECTS.orange.viewed){setTimeout(()=>{g2.stage='agenda';g2Render()},450)}};
gate2TestEntry=function(){g2={stage:null,selected:null,agenda:[],branch:{},sign:18,pieces:[],order:[],folder:[]};Object.values(GATE2_BILL_OBJECTS).forEach(x=>{x.viewed=false;x.marks=[];x.status='draft'});l2={...L2,gate2Started:true};lsave();render2()};
