/* 僅由 /gate-2/ 載入的開發入口：不改第一關，並固定由第二關開場測試。 */
function gate2TestEntry(){l2={...L2,gate2Started:true};lsave();render2()}
const gate2TestShell=shell;
shell=function(title,body,step=''){gate2TestShell(title,body,step);let buttons=document.querySelectorAll('.l2top .mini');if(buttons[0]){buttons[0].textContent='↺ 重新測試';buttons[0].onclick=gate2TestEntry}if(buttons[1]){buttons[1].textContent='測試入口';buttons[1].onclick=gate2TestEntry}};
complete=function(){shell('程序完成',`<div class="complete2"><div class="stampbig">程序完成</div><h1>尚未完成的法案</h1><div class="flow">提案 ↓ 程序委員會 ↓ 一讀<br>委員會審查 ─┐<br>逕付二讀 → 黨團協商 ─┴→ 二讀 → 三讀 → 公布 → 生效</div><p>第二關測試完成。</p><button class="btn light" onclick="gate2TestEntry()">重新測試第二關</button><button class="btn" onclick="gate2TestEntry()">返回測試入口</button></div>`,'完成')};
/* 等第一關啟動時既有的提示結束後，再清楚切入本關測試畫面。 */
/* 開場改為同一個可左右探索的議事場景；後續程序暫維持既有實作。 */
function viewProposal(id){l2.openedBills=l2.openedBills||[];if(!l2.openedBills.includes(id))l2.openedBills.push(id);lsave();let b=LEVEL2_CONTENT.bills[id];document.querySelector('#explore-paper')?.remove();let p=document.createElement('article');p.id='explore-paper';p.className=`desk-paper ${id}`;p.innerHTML=`<button aria-label="收起文件" onclick="this.parentElement.remove()">×</button><em>${b.tag}</em><h2>${b.name}</h2><p>${b.by}</p><small>已收入待處理文件夾</small>`;document.querySelector('.explore-world').append(p);document.querySelector('#file-count').textContent=`待處理文件 ${l2.openedBills.length} / 2`;if(l2.openedBills.length===2)document.querySelector('#to-procedure').classList.remove('hidden')}
function exploreMove(side){let p=document.querySelector('#explore-pan');p?.scrollTo({left:side==='left'?0:p.scrollWidth-p.clientWidth,behavior:'smooth'})}
intro=function(){app.innerHTML=`<section class="explore-level"><div class="arrival"><b>貳｜尚未完成的法案</b><span>兩份尚未完成的立法紀錄，散落在這裡。</span></div><header class="explore-top"><small id="file-count">待處理文件 ${(l2.openedBills||[]).length} / 2</small></header><div class="explore-pan" id="explore-pan"><div class="explore-world"><button class="scene-file file-blue" onclick="viewProposal('blue')" aria-label="查看政府案文件"><span>政府案</span><b>校園安全管理法<br>部分條文修正草案</b><small>行政院</small></button><button class="scene-file file-orange" onclick="viewProposal('orange')" aria-label="查看委員案文件"><span>委員案</span><b>校園安全管理法<br>第十二、十五、十八條修正草案</b><small>陳○○等｜連署17人</small></button></div></div><nav class="explore-nav"><button onclick="exploreMove('left')">〈 委員會工作區</button><button onclick="exploreMove('right')">院會程序區 〉</button></nav><button id="to-procedure" class="btn explore-next ${(l2.openedBills||[]).length===2?'':'hidden'}" onclick="l2.proposalChecked=true;l2.stage='procedure';lsave();render2()">將文件送往程序桌</button></section>`};
const openProposal=viewProposal;
viewProposal=function(id){openProposal(id);document.querySelector(`.file-${id}`)?.classList.add('collected')};
setTimeout(gate2TestEntry,0);

/* 第一幕的法案物件資料：後續各程序只需更新 status、marks、attachments，即可改變外觀。 */
window.GATE2_BILL_OBJECTS=window.GATE2_BILL_OBJECTS||{
 blue:{id:'blue',kind:'government',status:'draft',viewed:false,marks:[],attachments:['修正條文對照表'],returnTo:'左側議事桌'},
 orange:{id:'orange',kind:'member',status:'draft',viewed:false,marks:[],attachments:['連署頁'],returnTo:'右側議事桌'}
};
function billObject(id){return window.GATE2_BILL_OBJECTS[id]}
function returnProposal(id){let open=document.querySelector('#proposal-open');if(!open)return;open.classList.add('returning');setTimeout(()=>{open.remove();document.querySelector(`.document-${id}`)?.classList.remove('is-lifted')},310)}
function viewProposal(id){let item=billObject(id),b=LEVEL2_CONTENT.bills[id];item.viewed=true;document.querySelectorAll('#proposal-open').forEach(x=>x.remove());document.querySelector(`.document-${id}`)?.classList.add('is-lifted');let p=document.createElement('article');p.id='proposal-open';p.className=`proposal-open ${item.kind}`;p.innerHTML=`<div class="paper-stack"><div class="paper-sheet back"></div><div class="paper-sheet mid"></div><section class="paper-sheet cover"><button aria-label="將文件放回桌面" onclick="returnProposal('${id}')">×</button><em>${item.kind==='government'?'法律案':'委員提案'}</em><h2>${b.name}</h2><p>${b.by}</p><div class="paper-lines"></div>${item.kind==='member'?'<div class="signature-page">連署頁　｜　姓名欄　｜　連署欄</div>':'<small>修正條文對照表　・　附件資料</small>'}</section></div><p class="return-note">查看完畢後，將文件放回原本的議事桌。</p>`;document.querySelector('.explore-world').append(p)}
function enableExplorePan(){let pan=document.querySelector('#explore-pan');if(!pan||pan.dataset.bound)return;pan.dataset.bound='true';let held=false,x=0,left=0;pan.addEventListener('pointerdown',e=>{if(e.target.closest('.scene-document,.proposal-open'))return;held=true;x=e.clientX;left=pan.scrollLeft;pan.setPointerCapture?.(e.pointerId);pan.classList.add('dragging')});pan.addEventListener('pointermove',e=>{if(!held)return;pan.scrollLeft=left-(e.clientX-x)});['pointerup','pointercancel'].forEach(n=>pan.addEventListener(n,()=>{held=false;pan.classList.remove('dragging')}))}
function unlockExplore(){document.querySelector('.explore-level')?.classList.remove('intro-locked');document.querySelector('.swipe-cue')?.classList.add('visible')}
intro=function(){app.innerHTML=`<section class="explore-level intro-locked"><div class="story-subtitles"><span>本屆立法委員任期，即將屆滿。</span><span>但還有兩份修法紀錄，沒有走完。</span><span>在時間結束以前，找回它們的程序。</span><strong>貳｜尚未完成的法案</strong></div><div class="explore-pan" id="explore-pan"><div class="explore-world"><button class="scene-document document-blue" onclick="viewProposal('blue')" aria-label="拿起行政院提出的法律案"><div class="document-label"><em>法律案</em><b>校園安全管理法<br>部分條文修正草案</b><small>提案機關：行政院</small></div></button><button class="scene-document document-orange" onclick="viewProposal('orange')" aria-label="拿起委員提出的法律案"><div class="folder-tab">委員提案</div><div class="document-label"><b>校園安全管理法第十二條、<br>第十五條及第十八條條文修正草案</b><small>提案人：陳○○等<br>連署：17人</small><i>連署頁</i></div></button></div></div><span class="swipe-cue">左右滑動查看議場</span><nav class="explore-arrows"><button onclick="exploreMove('left')" aria-label="查看議場左側">‹</button><button onclick="exploreMove('right')" aria-label="查看議場右側">›</button></nav></section>`;enableExplorePan();setTimeout(unlockExplore,9800)};
function openGate2Folder(){modal(`<button class="close" onclick="document.querySelector('#modal')?.remove()">×</button><div class="gate2-folder-panel"><h2>文件夾</h2><p>目前沒有收入程序文件。</p><small>後續取得的連署名冊、審查報告與協商結論會收在這裡。</small></div>`)}
function positionChamberCenter(){let pan=document.querySelector('#explore-pan');if(pan)pan.scrollLeft=(pan.scrollWidth-pan.clientWidth)/2}
function updateDocumentHints(){let pan=document.querySelector('#explore-pan');if(!pan||document.querySelector('.explore-level')?.classList.contains('intro-locked'))return;document.querySelectorAll('.document-hint').forEach(h=>{let doc=document.querySelector(`.document-${h.dataset.bill}`),r=doc?.getBoundingClientRect(),visible=r&&Math.max(0,Math.min(r.right,innerWidth)-Math.max(r.left,0));h.classList.toggle('visible',!!r&&visible>Math.min(58,r.width*.38))})}
function bindChamberExplore(){enableExplorePan();let pan=document.querySelector('#explore-pan');pan?.addEventListener('scroll',updateDocumentHints);setTimeout(positionChamberCenter,0)}
function beginTracking(){document.querySelector('.story-dialogue')?.remove();document.querySelector('.explore-level')?.classList.remove('intro-locked');document.querySelector('.swipe-cue')?.classList.add('visible');updateDocumentHints()}
intro=function(){app.innerHTML=`<section class="explore-level intro-locked"><header class="gate2-hud"><div class="mission"><b>貳｜尚未完成的法案</b><br><span>立法程序紀錄</span></div><button class="folder-hud" onclick="openGate2Folder()" aria-label="開啟文件夾">▰<small>文件夾</small></button></header><div class="explore-pan" id="explore-pan"><div class="explore-world"><button class="scene-document document-blue" onclick="viewProposal('blue')" aria-label="拿起行政院提出的法律案"><div class="document-label"><em>法律案</em><b>校園安全管理法<br>部分條文修正草案</b><small>提案機關：行政院</small></div></button><span class="task-hint document-hint blue-hint" data-bill="blue"><i></i>查看文件</span><button class="scene-document document-orange" onclick="viewProposal('orange')" aria-label="拿起委員提出的法律案"><div class="folder-tab">委員提案</div><div class="document-label"><b>校園安全管理法第十二條、<br>第十五條及第十八條條文修正草案</b><small>提案人：陳○○等<br>連署：17人</small><i>連署頁</i></div></button><span class="task-hint document-hint orange-hint" data-bill="orange"><i></i>查看文件</span></div></div><div class="story-dialogue"><p>本屆立法委員任期即將屆滿。</p><p>但還有兩份修法紀錄，沒有走完。</p><p>在時間結束以前，把它們送回正確的程序。</p><button class="btn light" onclick="beginTracking()">開始追蹤</button></div><span class="swipe-cue">左右滑動查看議場</span><nav class="explore-arrows"><button onclick="exploreMove('left')" aria-label="查看議場左側">‹</button><button onclick="exploreMove('right')" aria-label="查看議場右側">›</button></nav></section>`;bindChamberExplore()};
