const L2_KEY='rules-city-level2-v1',L2={gate2Started:false,proposalChecked:false,procedureCommitteeDone:false,firstReadingDone:false,billsBranched:false,directSecondReadingDone:false,directBillSentToNegotiation:false,committeeReviewDone:false,committeeBillSentToNegotiation:false,negotiationDone:false,secondReadingDone:false,thirdReadingDone:false,promulgationDone:false,effectiveDateDone:false,gate2Completed:false,notebook02Unlocked:false,stage:'intro'};let l2={...L2,...JSON.parse(localStorage.getItem(L2_KEY)||'{}')},drag=null;
const lsave=()=>localStorage.setItem(L2_KEY,JSON.stringify(l2)),F=t=>{let e=document.querySelector('#l2f');if(e)e.textContent=t},B=(k,c='')=>{let b=LEVEL2_CONTENT.bills[k];return`<article class="bill ${k} ${c}" data-d="${k}" onclick="pick('${k}')"><em>${b.tag}</em><h3>${b.name}</h3><p>${b.by}</p></article>`};
function cityHall(){app.innerHTML=`<section class="hall"><button class="mini hall-notes" onclick="notesHub()">公民筆記</button><p>《規則之城》</p><h1>六道門大廳</h1><p>每一道門，都留著一段等待修復的公共生活紀錄。</p><div class="doors"><button class="hall-door" onclick="renderScene()"><b>壹</b><span>放學後的203</span><small>${state.checkoutCompleted?'已完成':'進入第一關'}</small></button><button class="hall-door ${l2.gate2Completed?'done':''}" onclick="gate2()"><b>貳</b><span>尚未完成的法案</span><small>${l2.gate2Completed?'已完成':'進入第二關'}</small></button>${['參','肆','伍','陸'].map(x=>`<div class="hall-door lock"><b>${x}</b><span>尚未開啟</span><small>鎖定</small></div>`).join('')}</div></section>`}
function notesHub(){modal(`<button class="close" onclick="cityHall()">×</button><div class="notebook-menu"><h2>公民筆記</h2><button ${state.checkoutCompleted?'onclick="review(0)"':''} ${state.checkoutCompleted?'':'disabled'}>公民筆記01｜社會規範 ${state.checkoutCompleted?'✓':'🔒'}</button><button ${l2.notebook02Unlocked?'onclick="notebook02()"':''} ${l2.notebook02Unlocked?'':'disabled'}>公民筆記02｜立法程序 ${l2.notebook02Unlocked?'✓':'🔒'}</button><button disabled>公民筆記03｜尚未開啟 🔒</button></div>`) }
function notebook02(){let a=LEVEL2_CONTENT.notebook.sections.map(x=>`<section><h3>${x[0]}</h3>${x[1].map(p=>`<p>${p}</p>`).join('')}</section>`).join('');modal(`<button class="close" onclick="cityHall()">×</button><article class="civic-notebook"><h2>${LEVEL2_CONTENT.notebook.title}</h2>${a}<button class="btn" onclick="cityHall()">收起筆記，返回大廳</button></article>`)}
function gate2(){l2.gate2Started=true;lsave();app.innerHTML='<div class="gate-fade"></div>';setTimeout(render2,260)}function shell(title,body,step=''){app.innerHTML=`<section class="legislature"><header class="l2top"><button class="mini" onclick="cityHall()">← 大廳</button><div><small>貳｜立法程序紀錄</small><b>${title}</b></div><button class="mini" onclick="notesHub()">筆記</button></header><main class="l2desk"><div class="l2step">${step}</div>${body}</main><div id="l2f" class="l2feedback"></div></section>`}
function render2(){({intro,procedure,first,branch,direct,directexit,committee,committeeexit,merge,negotiation,second,third,promulgation,effective,complete}[l2.stage]||intro)();bind()}
function intro(){shell('尚未完成的法案',`<div class="intro"><h1>尚未完成的法案</h1><p>兩份修法案的程序紀錄被打亂了。<br>在它們完成以前，把每一步送回正確的位置。</p></div><div class="bills">${B('blue')}${B('orange')}</div><button class="btn next" onclick="l2.proposalChecked=true;l2.stage='procedure';lsave();render2()">查看兩份文件，開始整理</button>`,'開場')}
function procedure(){shell('程序委員會',`<p class="prompt">法律案已經提出。下一站是哪裡？</p><div class="bills">${B('blue')}${B('orange')}</div><div class="zones"><button data-z="procedure" onclick="drop('procedure')">程序委員會</button><button data-z="committee" onclick="drop('committee')">委員會</button><button data-z="second" onclick="drop('second')">第二讀會</button></div>`,'提案 →')}
function first(){shell('第一讀會',`<p class="prompt">院會開始。第一讀會先進行哪一項？</p><div class="actions"><button onclick="firstPick('title')">朗讀議案標題</button><button onclick="firstPick('article')">逐條討論</button><button onclick="firstPick('vote')">全案表決</button></div>`,'程序委員會 → 一讀')}
function firstPick(x){if(x!=='title')return F('尚未進入該程序。');l2.firstReadingDone=true;l2.stage='branch';lsave();stamp('一讀完成 ✓',`${LEVEL2_CONTENT.bills.blue.name}<br>${LEVEL2_CONTENT.bills.orange.name}`)}
function branch(){shell('一讀後的分流',`<div class="rails">一讀 <i></i><b>藍案 → 委員會審查</b><b>橘案 → 逕付二讀</b></div><p class="prompt">把兩份程序紀錄送回它們的路線。</p><div class="bills">${B('blue')}${B('orange')}</div><div class="zones two"><button data-z="committee" onclick="drop('committee')">委員會審查</button><button data-z="direct" onclick="drop('direct')">逕付二讀</button></div>`,'一讀 → 分流')}
function direct(){let n=['林委員','許委員','周委員','方委員','吳委員'];shell('逕付二讀',`<p class="prompt">有人提議逕付二讀</p><p class="record">提議 ✓　連署／附議 <b>${18+(l2.sign||0)} / 20</b></p><p>拖兩張委員名牌進連署區。</p><div class="tags">${n.map((x,i)=>`<button data-d="sign${i}" onclick="pick('sign${i}')">${x}</button>`).join('')}</div><button class="signature" data-z="sign" onclick="drop('sign')">連署／附議區　${l2.sign||0}/2</button><button class="btn next" ${l2.sign===2?'':'disabled'} onclick="directVote()">院會表決</button>`,'逕付二讀')}
function directVote(){l2.directSecondReadingDone=true;l2.stage='directexit';delete l2.sign;lsave();stamp('逕付二讀','表決通過 ✓')}
function directexit(){shell('逕付二讀',`<p class="prompt">橘案前方出現兩個出口。</p>${B('orange')}<div class="zones two"><button data-z="second" onclick="drop('second')">第二讀會</button><button data-z="negotiation" onclick="drop('negotiation')">黨團協商</button></div>`,'逕付二讀 →')}
function committee(){shell('委員會審查',`<p class="prompt">把修正意見整理到正在審查的草案中。</p><div class="review"><article data-z="opinion" onclick="drop('opinion')"><b>原草案</b><p>${l2.opinion?'修正意見已夾入':'第十二條（審查中）'}</p></article><button data-d="opinion" onclick="pick('opinion')">修正意見</button><span>保留意見</span></div>${l2.opinion?'<button class="btn next" onclick="committeeDone()">整理審查文件</button>':''}`,'藍案 → 委員會審查')}
function committeeDone(){l2.committeeReviewDone=true;l2.stage='committeeexit';delete l2.opinion;lsave();stamp('審查完竣 ✓','部分條文仍有爭議。')}
function committeeexit(){shell('委員會審查報告',`<p class="prompt">本案紀錄已決議交付黨團協商。</p><small>委員會審查完竣後，議決是否交黨團協商。</small>${B('blue')}<div class="zones two"><button data-z="second" onclick="drop('second')">第二讀會</button><button data-z="negotiation" onclick="drop('negotiation')">黨團協商</button></div>`,'審查完竣 →')}
function merge(){shell('黨團協商',`<div class="merge"><div>${B('blue','move')}</div><div>${B('orange','move')}</div><strong>黨團協商桌</strong></div><p class="prompt">兩條程序路線，在同一張協商桌匯流。</p><button class="btn next" onclick="l2.stage='negotiation';lsave();render2()">修復協商紀錄</button>`,'兩案 → 黨團協商')}
function negotiation(){let p=['共同文字','協商紀錄','確認結論'];shell('黨團協商',`<p class="prompt">把被拆開的「黨團協商結論」拼回正確位置。</p><div class="tags">${p.map((x,i)=>`<button data-d="piece${i}" onclick="pick('piece${i}')">${x}</button>`).join('')}</div><button class="conclusion" data-z="piece" onclick="drop('piece')">${(l2.pieces||[]).join('　')||'黨團協商結論（空白）'}</button>`,'黨團協商 →')}
function second(){let p=['廣泛討論','逐條討論','條文議決'];shell('第二讀會',`<p class="prompt">排回本案的二讀程序。</p><div class="tags">${p.map(x=>`<button data-d="order:${x}" onclick="pick('order:${x}')">${x}</button>`).join('')}</div><button class="order" data-z="order" onclick="drop('order')">${(l2.order||[]).map((x,i)=>`${i+1}. ${x}`).join('<br>')||'1.　<br>2.　<br>3.　'}</button>`,'協商 → 二讀')}
function third(){shell('第三讀會',`<p class="prompt">二讀完成的法案，在桌燈下等待最後確認。</p><article class="amend"><b>第一張修正便條</b><p>原文：「違反者處新臺幣一萬元罰鍰。」</p><p>修正：「違反者處新臺幣十萬元罰鍰。」</p><button onclick="thirdPick('a1')">接受修正</button><button onclick="thirdPick('r1')">退回</button></article>${l2.t===1?'<article class="amend"><b>第二張修正便條</b><p>「應予以通知」 → 「應通知」</p><button onclick="thirdPick(\'a2\')">接受文字修正</button><button onclick="thirdPick(\'r2\')">退回</button></article>':''}${l2.t===2?'<button class="btn next" onclick="thirdVote()">全案表決</button>':''}`,'二讀 → 三讀')}
function thirdPick(x){if(x==='a1')return F('這不只是文字修正。');if(x==='r1'){l2.t=1;return render2()}if(x==='a2'){l2.t=2;return render2()}F('這是文字修正，可接受。')}
function thirdVote(){l2.thirdReadingDone=true;l2.stage='promulgation';delete l2.t;lsave();stamp('三讀通過','主席槌落下，全案表決通過。')}
function promulgation(){shell('三讀不是終點',`<div class="envelope"><h2>三讀通過！</h2><p>三讀通過 ✓<br>公布 □<br>生效 □</p><button class="btn" onclick="F('程序還沒有完成。')">完成</button><p>立法院咨請總統公布</p><button class="btn light" onclick="l2.promulgationDone=true;l2.stage='effective';lsave();stamp('總統公布 ✓','公布日期：10月12日')">確認公布紀錄</button></div>`,'三讀 → 公布')}
function effective(){shell('生效日',`<p class="prompt">把「生效」印章蓋在正確日期。</p><button class="ink" data-d="effective" onclick="pick('effective')">生效</button><div class="calendar">${['10/12|公布｜第一日','10/13|第二日','10/14|第三日','10/15|'].map((x,i)=>{let a=x.split('|');return`<button data-z="date${i}" onclick="drop('date${i}')"><b>${a[0]}</b><small>${a[1]}</small></button>`}).join('')}</div><p>自公布日起算至第三日起發生效力。</p>`,'公布 → 生效')}
function complete(){shell('程序完成',`<div class="complete2"><div class="stampbig">程序完成</div><h1>尚未完成的法案</h1><div class="flow">提案 ↓ 程序委員會 ↓ 一讀<br>委員會審查 ─┐<br>逕付二讀 → 黨團協商 ─┴→ 二讀 → 三讀 → 公布 → 生效</div><p>第二道門已解鎖。</p><button class="btn light" onclick="notebook02()">開啟公民筆記02</button><button class="btn" onclick="cityHall()">返回六道門大廳</button></div>`,'完成')}
function stamp(s,m){shell('尚未完成的法案',`<div class="stampview"><div class="stampbig">${s}</div><p>${m}</p></div>`);setTimeout(render2,800)}
function pick(x){drag=x;document.querySelectorAll('[data-d]').forEach(e=>e.classList.toggle('picked',e.dataset.d===x))}
function drop(z){if(!drag)return;let x=drag;drag=null;if(l2.stage==='procedure'){if(z!=='procedure')return F(z==='committee'?'尚未經院會交付。':'程序尚未走到這裡。');l2['p'+x]=true;if(!(l2.pblue&&l2.porange))return render2();l2.procedureCommitteeDone=true;l2.stage='first';delete l2.pblue;delete l2.porange;lsave();return stamp('議事日程審定 ✓','兩份文件進入院會。')}if(l2.stage==='branch'){if(!((x==='blue'&&z==='committee')||(x==='orange'&&z==='direct')))return F('這份紀錄的交付方向不在這裡。');l2[x]=true;if(l2.blue&&l2.orange){l2.billsBranched=true;l2.stage='direct';delete l2.blue;delete l2.orange;lsave();return stamp('兩案分流 ✓','兩份文件沿不同程序軌道前進。')}return render2()}if(l2.stage==='direct'&&x.startsWith('sign')&&z==='sign'){l2.sign=Math.min(2,(l2.sign||0)+1);return render2()}if(l2.stage==='directexit'){if(z!=='negotiation')return F('程序尚未完成。逕付二讀議案應交付黨團協商。');l2.directBillSentToNegotiation=true;l2.stage='committee';lsave();return stamp('交付黨團協商','橘案暫停在協商桌等待。')}if(l2.stage==='committee'&&x==='opinion'&&z==='opinion'){l2.opinion=true;return render2()}if(l2.stage==='committeeexit'){if(z!=='negotiation')return F('本案紀錄：決議交付黨團協商。');l2.committeeBillSentToNegotiation=true;l2.stage='merge';lsave();return stamp('交付黨團協商','藍案正前往協商桌。')}if(l2.stage==='negotiation'&&x.startsWith('piece')&&z==='piece'){l2.pieces=l2.pieces||[];let p=['共同文字','協商紀錄','確認結論'][+x.slice(5)];if(!l2.pieces.includes(p))l2.pieces.push(p);if(l2.pieces.length===3){l2.negotiationDone=true;l2.stage='second';delete l2.pieces;lsave();return stamp('黨團協商完成 ✓','不同意見文件疊合成完整結論。')}return render2()}if(l2.stage==='second'&&x.startsWith('order:')&&z==='order'){l2.order=l2.order||[];let p=x.slice(6);if(!l2.order.includes(p))l2.order.push(p);if(l2.order.length===3){if(l2.order.join('|')!=='廣泛討論|逐條討論|條文議決'){l2.order=[];F('程序順序似乎不對。');return setTimeout(render2,600)}l2.secondReadingDone=true;l2.stage='third';delete l2.order;lsave();return stamp('二讀完成','廣泛討論 ✓　逐條討論 ✓　條文議決 ✓')}return render2()}if(l2.stage==='effective'&&x==='effective'){if(z!=='date2')return F('再看一次公布日的起算方式。');l2.effectiveDateDone=l2.gate2Completed=l2.notebook02Unlocked=true;l2.stage='complete';lsave();return stamp('法律生效 ✓','10/12 第一日　10/13 第二日　10/14 第三日')}}
function bind(){document.querySelectorAll('[data-d]').forEach(e=>e.addEventListener('pointerdown',v=>{pick(e.dataset.d);e.setPointerCapture?.(v.pointerId);v.preventDefault()}));document.querySelectorAll('[data-z]').forEach(e=>e.addEventListener('pointerup',v=>{if(drag){drop(e.dataset.z);v.preventDefault()}}))}
/* #level2 會直接續玩；#level2-reset 僅清除第二關的開發測試狀態。 */
setTimeout(()=>window.__GATE2_TEST__?null:location.hash==='#level2-reset'?(l2={...L2},lsave(),gate2()):location.hash==='#level2'?gate2():cityHall(),0);
