(()=>{
const K='rules-city-gate4-v1',app=document.querySelector('#app'),fresh=()=>({rev:2,shuffleVersion:1,phase:'title',docs:{},docOrder:null,collective:false,sources:{},sourceOrder:null,rights:{},rightOrder:null,wind:0,windReady:false,sourceEntered:false,complete:false});let old=JSON.parse(localStorage.getItem(K)||'{}'),s=old.rev===2?Object.assign(fresh(),old):fresh(),selected=null;if(old.shuffleVersion!==1){s.docOrder=null;s.sourceOrder=null;s.rightOrder=null;s.shuffleVersion=1}const save=()=>localStorage.setItem(K,JSON.stringify(s));
const shuffle=list=>{let a=[...list];for(let i=a.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
const shuffleMixed=(list,key)=>{for(let n=0;n<40;n++){let a=shuffle(list);if(a.every((v,i)=>i===0||key(v)!==key(a[i-1])))return a}return shuffle(list)};
const scene=(x,k='')=>`<div class="room ${k}"></div><div class="shade"></div><header><span>GATE 4<br><b>權利檔案室</b></span><nav class="gate4-nav" aria-label="關卡選單"><button class="gate4-menu-toggle" data-a="menu-toggle" aria-label="開啟關卡選單" aria-expanded="false">☰</button><div class="gate4-menu" role="menu"><button data-a="menu-return" role="menuitem">返回規則之城</button><button data-a="menu-restart" role="menuitem">重新開始本關</button><button data-a="menu-close" role="menuitem">關閉</button></div></nav></header>${x}`,modal=x=>`<section class="closeup"><button class="x" data-a="close">×</button>${x}</section>`;
const docs={student:['高中生小安','學生證／基本資料影本','natural','自然人',''],assoc:['幸福教育協會','協會卷宗','private','私法人','社團法人'],found:['兒童福利基金會','基金會卷宗','private','私法人','財團法人'],nation:['中華民國','中央政府正式文件','public','公法人','國家'],local:['新北市','地方政府公文','public','公法人','地方自治團體'],admin:['國家表演藝術中心','設立文件／機關資料','public','公法人','行政法人']};
const sources={speech:['言論自由','校刊剪報','list'],privacy:['隱私權','個資列印資料','general'],vote:['選舉權','投票相關文件','list'],person:['人格權','姓名與肖像資料','general'],suit:['訴訟權','法院文件','list']};
const rights=[['學校開放學生會長選舉，男女學生都有相同的參選資格。','平等權','不因性別而受到不合理差別待遇'],['身心障礙考生可依需要申請延長考試時間或使用輔具。','平等權','合理差別待遇'],['警方不能沒有法律依據，就把人民拘留在派出所。','自由權','人身自由'],['學生在校刊上評論公共政策，不會只因意見不同就被禁止發表。','自由權','言論自由'],['小安可以信仰宗教，也可以選擇不信仰任何宗教。','自由權','宗教自由'],['阿哲認為政府的處分侵害他的權利，因此向法院請求救濟。','受益權','訴訟權｜司法上的受益'],['學生依法接受教育，不因家庭經濟狀況而失去基本的受教機會。','受益權','受教育權'],['阿明發生符合勞工保險規定的事故後，依法申請保險給付。','受益權','經濟上的受益'],['20歲的小宇在選舉日到投票所，投下自己的一票。','參政權','選舉權'],['小芸報名公務人員考試，希望通過考試後進入政府機關服務。','參政權','應考試服公職權']];
function render(){save();if(s.complete)return finish();({title,intro,subject,wind,collective,sourceIntro,source,rights:challenge,final}[s.phase]||title)()}
function title(){app.innerHTML=scene(`<button class="file-cover" data-a="open" aria-label="開啟權利檔案室卷宗"><span class="cover-art" aria-hidden="true"></span><span class="cover-print"><small>GATE 4</small><strong>權利檔案室</strong><em>未完成之憲法權利資料</em></span></button>`)}
function intro(){app.innerHTML=scene(`<article class="opened-file"><h1>這批資料還沒有整理完成。</h1><p>請確認：<br><b>誰能主張？</b><br><b>權利從哪裡來？</b><br><b>它屬於哪一類？</b></p><button class="ink" data-a="begin">開始整理</button><small>這關很簡單～～～</small></article>`)}
function subject(){if(!s.docOrder){s.docOrder=shuffleMixed(Object.keys(docs),id=>docs[id][2]);save()}let n=Object.keys(s.docs).length,files=s.docOrder.map((id,i)=>{let d=docs[id];return `<button class="desk-doc d${i} ${s.docs[id]?'filed':''}" data-doc="${id}"><small>${d[1]}</small><b>${d[0]}</b>${s.docs[id]?'<i>已歸檔</i>':''}</button>`}).join('');app.innerHTML=scene(`<main class="desk-stage"><p class="note">桌上的資料尚未歸檔。點一份文件，再放進正確資料夾。</p>${files}<div class="folders"><button data-folder="natural">自然人</button><button data-folder="private">私法人</button><button data-folder="public">公法人</button></div>${n===6?'<button class="result-sheet" data-a="subject-done">權利主體<br><small>分類成果已整理完成</small></button>':''}<p class="hint"></p></main>`)}
function openDoc(id){let d=docs[id],p=id==='assoc'?'由會員組成，以推動教育公益活動為目的。':id==='found'?'由捐助財產設立，投入兒童福利工作。':id==='admin'?'依法設立，負責國家級表演藝術場館及相關公共事務。':'請確認這份文件應歸入哪一個資料夾。';app.insertAdjacentHTML('beforeend',modal(`<div class="document"><small>${d[1]}</small><h2>${d[0]}</h2><p>${p}</p><div class="mini-folders"><button data-folder="natural">自然人</button><button data-folder="private">私法人</button><button data-folder="public">公法人</button></div><p class="hint">選擇歸檔資料夾。</p></div>`))}
function folder(f,id){let d=docs[id];if(f!==d[2])return feedback(document.querySelector(`.mini-folders button[data-folder="${f}"]`)||document.querySelector(`.folders button[data-folder="${f}"]`),'再看看這份文件的性質與設立基礎。');if(f==='natural'){s.docs[id]='自然人';selected=null;render();return}let op=f==='private'?['社團法人','財團法人']:['國家','地方自治團體','行政法人'];app.insertAdjacentHTML('beforeend',modal(`<div class="folder-open"><h2>${f==='private'?'私法人':'公法人'}資料夾</h2><p>選擇分隔頁完成歸檔。</p>${op.map(x=>`<button class="tab" data-sub="${x}">${x}</button>`).join('')}<p class="hint"></p></div>`))}
function wind(){let ps=['幸福教育協會','兒童福利基金會','新北市','國家表演藝術中心'];let papers=ps.map((x,i)=>`<div class="wind-paper w${i}">${x}</div>`).join('');let reveal=s.windReady?`<button class="unfiled-case" data-a="open-unfiled"><b>未歸檔</b></button>`:'';app.innerHTML=scene(`<main class="wind-stage auto-wind"><p>${s.windReady?'風吹過後，桌面露出一份陌生卷宗。':'窗外吹進一陣風。'}</p>${s.windReady?`<div class="recovered-stack">幾份文件被風吹開。</div>${reveal}`:papers}<small>${s.windReady?'點開這份卷宗。':''}</small></main>`);if(!s.windReady)setTimeout(()=>{if(s.phase==='wind'&&!s.windReady){s.windReady=true;render()}},950)}
function collective(){app.innerHTML=scene(`<main class="case-stage"><article class="case-file"><small>未歸檔</small><h1>傳統領域開發案</h1><p>某開發計畫涉及原住民族傳統領域。當地部落認為，這不只是某一位族人的個人利益，而會影響整個部落的土地、文化與生活方式。</p>${s.collective?`<b class="red-stamp">原住民族集體權利</b><p>有些權利不是由單一個人各自主張，而是由群體共同享有或行使。</p><button class="ink" data-a="to-source-intro">收進資料夾</button>`:`<h2 class="case-question">這個案例主要涉及哪一種權利？</h2><div><button class="stamp" data-col="individual">個人權利</button><button class="stamp" data-col="group">集體權利</button></div><p class="hint"></p>`}</article></main>`)}
function sourceIntro(){app.innerHTML=scene(`<main class="source-transition"><article class="closing-file"><small>傳統領域開發案</small><b>卷宗已收起</b></article><p class="transition-message">接下來，確認這些權利在憲法中的保障方式。</p></main>`,'lookup-push');setTimeout(()=>{if(s.phase==='sourceIntro'){s.phase='source';render()}},2650)}
function source(){if(!s.sourceOrder){s.sourceOrder=shuffleMixed(Object.keys(sources),id=>sources[id][2]);save()}let first=!s.sourceEntered;s.sourceEntered=true;let all=s.sourceOrder.map(id=>[id,sources[id]]),left=all.filter(([id])=>!s.sources[id]);let ev=all.map(([id,d],i)=>s.sources[id]?`<div class="evidence e${i} filed"><small>${d[1]}</small><b>${d[0]}</b><i>已歸檔</i></div>`:`<button class="evidence e${i}" data-src="${id}"><small>${d[1]}</small><b>${d[0]}</b></button>`).join('');let state=left.length?(first?'lookup-arrive':'lookup-static'):'lookup-complete';app.innerHTML=scene(`<main class="lookup ${state}"><p class="note">請判斷：這項權利是憲法明文列舉，還是由第22條概括保障？</p><button class="law list" data-law="list"><b>中華民國憲法</b><span>憲法明文列舉</span></button><button class="law general" data-law="general"><b>第 22 條</b><span>第22條概括保障</span><em>其他自由及權利</em></button>${left.length?ev:`${ev}<div class="source-finished">五份權利資料已完成歸檔。</div><button class="ink next" data-a="to-rights">前往快速歸檔挑戰</button>`}<p class="hint"></p></main>`)}
let rightPick=null,rightNote='',rightLocked=false;const rightLabels=['學生會參選','考試調整','派出所拘留','校刊評論','宗教信仰','法院救濟','受教育','勞保給付','選舉投票','公務人員考試'];
function challenge(){if(!s.rightOrder){s.rightOrder=shuffleMixed(rights.map((_,i)=>i),i=>rights[i][1]);save()}let i=s.rightOrder.find(n=>!s.rights[n]);if(i===undefined){app.innerHTML=scene(`<main class="drawer-stage summary"><div>平等權<small>相同者相同，不同者得合理區別</small></div><div>自由權<small>保障人民自主活動的空間</small></div><div>受益權<small>得依法請求國家提供救濟、制度或給付</small></div><div>參政權<small>參與國家政治與公務</small></div></main>`);setTimeout(()=>{if(s.phase==='rights'){s.phase='final';render()}},3200);return}app.innerHTML=scene(`<main class="drawer-stage"><p>快速歸檔挑戰</p><article class="scenario"><small>待歸檔生活情境</small><b>${rights[i][0]}</b></article><div class="drawers">${['平等權','自由權','受益權','參政權'].map(x=>`<button data-drawer="${x}">${x}</button>`).join('')}</div><p class="hint"></p></main>`,'cabinet')}
function final(){app.innerHTML=scene(`<main class="final-desk"><article class="final-file"><h1>憲法權利總檔案</h1><p>✓ 權利主體<br>✓ 集體權利<br>✓ 列舉／概括基本權<br>✓ 四大基本權</p><p><b>最終確認：＿＿＿＿</b></p><button class="stamp" data-a="confirm">權利確認</button></article></main>`)}
function finish(){app.innerHTML=`<main class="complete"><article><small>GATE 4</small><h1>已歸檔</h1><b class="red-stamp">權利確認</b><h2>GATE 4 COMPLETE</h2><p>先確認「誰能主張」，<br>才能進一步討論國家能不能限制。</p><div class="gate4-finish-actions"><button class="ink" data-a="return-hub">返回規則之城</button><button class="plain" data-a="restart">重新挑戰本關</button></div></article></main>`}
function clearTransient(){document.querySelector('#error-toast')?.remove();document.querySelector('#archive-toast')?.remove();rightNote=''}
function archiveToast(text){document.querySelector('#archive-toast')?.remove();app.insertAdjacentHTML('beforeend',`<div id="archive-toast" class="archive-toast">${text}</div>`)}
function feedback(target,text){target?.classList.remove('shake');void target?.offsetWidth;target?.classList.add('shake');setTimeout(()=>target?.classList.remove('shake'),460);document.querySelector('#error-toast')?.remove();app.insertAdjacentHTML('beforeend',`<div id="error-toast" class="error-toast">${text}</div>`);setTimeout(()=>document.querySelector('#error-toast')?.classList.add('fade-away'),2300);setTimeout(()=>document.querySelector('#error-toast')?.remove(),2900)}
function hint(t){feedback(null,t)}
document.addEventListener('click',e=>{let b=e.target.closest('button');if(!b)return;let a=b.dataset.a;if(a==='open'){s.phase='intro';render()}else if(a==='begin'){s.phase='subject';render()}else if(a==='close'){b.closest('.closeup,.confirm')?.remove()}else if(a==='restart'){let finished=s.complete;app.insertAdjacentHTML('beforeend',`<section class="confirm"><h2>${finished?'確定要重新挑戰本關嗎？':'確定要重新開始本關嗎？'}</h2><p>${finished?'本關目前進度將重新開始。':'要清除第四關的進度並重新開始嗎？'}</p><button class="ink" data-a="reset">${finished?'重新挑戰':'確認清除'}</button><button class="plain" data-a="close">${finished?'取消':'保留進度'}</button></section>`)}else if(a==='reset'){s=fresh();selected=null;rightPick=null;rightLocked=false;clearTransient();render()}else if(a==='subject-done'){s.phase='wind';render()}else if(a==='open-unfiled'){s.phase='collective';render()}else if(a==='to-source-intro'){s.phase='sourceIntro';render()}else if(a==='to-rights'){rightPick=null;rightNote='';rightLocked=false;s.phase='rights';render()}else if(a==='confirm'){s.complete=true;render()}
let id=b.dataset.doc;if(id){clearTransient();selected=id;openDoc(id)}let f=b.dataset.folder;if(f&&selected)folder(f,selected);let sub=b.dataset.sub;if(sub&&selected){let d=docs[selected];if(sub===d[4]){s.docs[selected]=sub;selected=null;document.querySelectorAll('.closeup').forEach(x=>x.remove());render()}else{let msg=selected==='assoc'?'再想想：這個組織是由「會員」組成，還是由「捐助財產」設立？':selected==='found'?'注意資料中的關鍵字：「由捐助財產設立」。':'再看看這份文件的成立基礎或公共任務。';feedback(b.closest('.folder-open'),msg)}}
let c=b.dataset.col;if(c){if(c==='group'){s.collective=true;render()}else feedback(b,'再想想：這項利益影響的是單一族人，還是整個部落共同的土地、文化與生活方式？')}
let q=b.dataset.src;if(q){clearTransient();selected=q;app.insertAdjacentHTML('beforeend',modal(`<div class="document"><small>${sources[q][1]}</small><h2>${sources[q][0]}</h2><p>確認這份資料的憲法保障基礎。</p><div class="mini-folders"><button data-law="list">憲法明文列舉</button><button data-law="general">第22條概括保障</button></div></div>`))}let l=b.dataset.law;if(l&&selected){if(l===sources[selected][2]){s.sources[selected]=l;selected=null;document.querySelectorAll('.closeup').forEach(x=>x.remove());render()}else feedback(b,selected==='privacy'?'找找看，憲法本文有直接寫出「隱私權」嗎？':'有些重要權利並未直接列出名稱，而是由第22條提供保障基礎。')}
let d=b.dataset.drawer;if(d&&!rightLocked){let i=s.rightOrder?.find(n=>!s.rights[n]);if(d===rights[i][1]){rightLocked=true;clearTransient();archiveToast(rights[i][2]);s.rights[i]=true;setTimeout(()=>{if(s.phase==='rights'){rightLocked=false;clearTransient();render()}},850)}else feedback(b,i===7?'這裡的重點是：人民依法向制度請求給付。':'再讀一次情境，找出它著重保障的權利。')}});render();
})();
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const a=b.dataset.a;if(a==='return-hub'){window.location.assign('../index.html');return}if(a==='menu-toggle'){const open=!app.classList.contains('gate4-menu-open');app.classList.toggle('gate4-menu-open',open);b.setAttribute('aria-expanded',String(open));return}if(a==='menu-close'){app.classList.remove('gate4-menu-open');return}if(a==='menu-return'){app.classList.remove('gate4-menu-open');app.insertAdjacentHTML('beforeend',`<section class="confirm gate4-menu-confirm"><h2>確定要返回規則之城嗎？</h2><p>本關目前進度不會保留。</p><div class="gate4-confirm-actions"><button class="plain" data-a="close">繼續本關</button><button class="ink" data-a="confirm-menu-return">返回規則之城</button></div></section>`);return}if(a==='menu-restart'){app.classList.remove('gate4-menu-open');app.insertAdjacentHTML('beforeend',`<section class="confirm gate4-menu-confirm"><h2>確定要重新開始本關嗎？</h2><p>本關目前進度將重新開始。</p><div class="gate4-confirm-actions"><button class="plain" data-a="close">取消</button><button class="ink" data-a="confirm-menu-restart">重新開始</button></div></section>`);return}if(a==='confirm-menu-return'){localStorage.removeItem('rules-city-gate4-v1');window.location.assign('../index.html');return}if(a==='confirm-menu-restart'){localStorage.removeItem('rules-city-gate4-v1');window.location.reload()}});document.addEventListener('click',e=>{if(!e.target.closest('.gate4-nav'))app.classList.remove('gate4-menu-open')});
